// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeogPni4iuzD8zA6HCkf73-8_cb0aUAMg',
    appId: '1:823394604047:web:43904927ae50822478bf7a',
    messagingSenderId: '823394604047',
    projectId: 'fruit-app-b319f',
    authDomain: 'fruit-app-b319f.firebaseapp.com',
    storageBucket: 'fruit-app-b319f.firebasestorage.app',
    measurementId: 'G-45D58NJ6PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVEfFTtfjrxBaJ_1vOKzxdtKsltNixaQ',
    appId: '1:823394604047:android:4d03b99940abf5e678bf7a',
    messagingSenderId: '823394604047',
    projectId: 'fruit-app-b319f',
    storageBucket: 'fruit-app-b319f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUD1LV8u3oTo7wOkrcZms_UmGCh9HZ-5k',
    appId: '1:823394604047:ios:b6c78f4c5c2e4f7978bf7a',
    messagingSenderId: '823394604047',
    projectId: 'fruit-app-b319f',
    storageBucket: 'fruit-app-b319f.firebasestorage.app',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUD1LV8u3oTo7wOkrcZms_UmGCh9HZ-5k',
    appId: '1:823394604047:ios:b6c78f4c5c2e4f7978bf7a',
    messagingSenderId: '823394604047',
    projectId: 'fruit-app-b319f',
    storageBucket: 'fruit-app-b319f.firebasestorage.app',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeogPni4iuzD8zA6HCkf73-8_cb0aUAMg',
    appId: '1:823394604047:web:9fe2e8c0a20aab5f78bf7a',
    messagingSenderId: '823394604047',
    projectId: 'fruit-app-b319f',
    authDomain: 'fruit-app-b319f.firebaseapp.com',
    storageBucket: 'fruit-app-b319f.firebasestorage.app',
    measurementId: 'G-D1RYQ000XY',
  );
}
